<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class OmieMF extends Model
{
    protected $table = 'omie_mf';

    protected $fillable = [
        'empresa',
        'nCodTitulo',
        'cCodIntTitulo',
        'cNumTitulo',
        'dDtEmissao',
        'dDtVenc',
        'dDtPrevisao',
        'dDtPagamento',
        'nCodCliente',
        'cCPFCNPJCliente',
        'nCodCtr',
        'cNumCtr',
        'nCodOS',
        'cNumOS',
        'nCodCC',
        'cStatus',
        'cNatureza',
        'cTipo',
        'cOperacao',
        'cNumDocFiscal',
        'cCodCateg',
        'cNumParcela',
        'nValorTitulo',
        'nValorPIS',
        'cRetPIS',
        'nValorCOFINS',
        'cRetCOFINS',
        'nValorCSLL',
        'cRetCSLL',
        'nValorIR',
        'cRetIR',
        'nValorISS',
        'cRetISS',
        'nValorINSS',
        'cRetINSS',
        'cCodProjeto',
        'observacao',
        'cCodVendedor',
        'nCodComprador',
        'cCodigoBarras',
        'cNSU',
        'nCodNF',
        'dDtRegistro',
        'cNumBoleto',
        'cChaveNFe',
        'cOrigem',
        'nCodTitRepet',
        'cGrupo',
        'nCodMovCC',
        'nValorMovCC',
        'nCodMovCCRepet',
        'nDesconto',
        'nJuros',
        'nMulta',
        'nCodBaixa',
        'dDtCredito',
        'dDtConcilia',
        'cHrConcilia',
        'cUsConcilia',
        'dDtInc',
        'cHrInc',
        'cUsInc',
        'dDtAlt',
        'cHrAlt',
        'cUsAlt',
        'payload',
    ];

    protected $casts = [
        'payload' => 'array',
        'dDtEmissao' => 'date',
        'dDtVenc' => 'date',
        'dDtPrevisao' => 'date',
        'dDtPagamento' => 'date',
        'dDtRegistro' => 'date',
        'dDtCredito' => 'date',
        'dDtConcilia' => 'date',
        'dDtInc' => 'date',
        'dDtAlt' => 'date',
    ];
}
