<?php

namespace App\Repositories;

use Illuminate\Support\Facades\DB;

class RecebimentosRepository
{
    public function listarRecebimentos($dtInicial, $dtFinal)
    {
        $sql = "
            DECLARE @DT_INICIAL DATE = :dtInicial;
            DECLARE @DT_FINAL   DATE = :dtFinal;

            ---------------------------------------------------------
            -- SUA QUERY COMPLETA (SEM NENHUMA ALTERAÇÃO)
            ---------------------------------------------------------

           USE EASYCOLLECTOR
GO

DECLARE	@DT_INICIAL			AS	DATE
DECLARE	@DT_FINAL			AS	DATE
SET		@DT_INICIAL			=	'2025-11-19'
SET		@DT_FINAL			=	'2025-12-15'


---CAPACITY
IF OBJECT_ID('TEMPDB.DBO.#TB_TEMP_CAPACITY', 'U') IS NOT NULL
DROP TABLE #TB_TEMP_CAPACITY
SELECT
		  NU_CPF_CNPJ	=	CAST(IDNUMBER AS BIGINT)
		, NM_NOME		=	NAME
		, DT_ADMISSAO	=	DATEADMISSION
		, CARTEIRA		=	UPPER(DEPARTMENT	)
		, POSICAO		=	UPPER(POSITION		)
		, TIPO			=	UPPER(TYPECONTRACT	)
		, META_PONTO	=	CAST(NULL AS DECIMAL(18,2))
INTO	#TB_TEMP_CAPACITY
FROM	[192.168.1.71].[DB_MIS].[DBO].[TB_CAPACITY_SOLIDES]	WITH(NOLOCK)
WHERE
		DT_REF	=	@DT_INICIAL
	AND DATEDISMISSAL IS NULL



---PAGTO ANALITICO
IF OBJECT_ID('TEMPDB.DBO.#TB_TEMP_PAGAMENTOS_ANALITICO', 'U') IS NOT NULL
DROP TABLE #TB_TEMP_PAGAMENTOS_ANALITICO
SELECT
		  NU_CPF_CNPJ		=	U.NM_CPF
		, U.NM_USUARIO
		, F.ID_CLIENTE
		, F.ID_FATURA
		, DT_PAGAMENTO		=	CAST(F.DT_PAGAMENTO AS DATE)
		, F.VL_PAGO
INTO	#TB_TEMP_PAGAMENTOS_ANALITICO
FROM	TB_FATURA	F WITH(NOLOCK)
		INNER JOIN
		TB_ACORDO	A WITH(NOLOCK)
ON		F.ID_CLIENTE	=	A.ID_CLIENTE
	AND F.ID_ACORDO		=	A.ID_ACORDO
		LEFT JOIN
		TB_USUARIO	U WITH(NOLOCK)
ON		A.ID_USUARIO	=	U.ID_USUARIO
WHERE
		CAST(F.DT_PAGAMENTO AS DATE) BETWEEN @DT_INICIAL AND @DT_FINAL
	AND F.NU_PARCELA	=	1

--IDENTIFICA AS ACOES POSITIVAS DO PREVENTIVO
IF OBJECT_ID('TEMPDB.DBO.#TB_TEMP_PAGAMENTOS_ANALITICO_PREVENTIVO', 'U') IS NOT NULL
DROP TABLE #TB_TEMP_PAGAMENTOS_ANALITICO_PREVENTIVO
SELECT
		  C.NM_CEDENTE
		, CA.ID_CLIENTE
		, PA.ID_FATURA
		, PA.DT_PAGAMENTO
		, CA.ID_CLIENTE_ACAO
		, DT_ACAO				=	CAST(CA.DT_ACAO AS DATE)
		, CA.ID_USUARIO
		, NU_CPF_CNPJ		=	U.NM_CPF
		, U.NM_USUARIO
		, PA.VL_PAGO		
		, NU_ORDEM_PREVENTIVO	=	ROW_NUMBER() OVER (PARTITION BY CA.ID_CLIENTE, PA.ID_FATURA ORDER BY ID_CLIENTE_ACAO DESC)
INTO	#TB_TEMP_PAGAMENTOS_ANALITICO_PREVENTIVO
FROM	TB_CLIENTE_ACAO					CA	WITH(NOLOCK)
		INNER JOIN
		#TB_TEMP_PAGAMENTOS_ANALITICO	PA	
ON		CA.ID_CLIENTE = PA.ID_CLIENTE
		INNER JOIN 
		TB_USUARIO						U	WITH(NOLOCK)
ON		CA.ID_USUARIO	=	U.ID_USUARIO
		INNER JOIN
		TB_CLIENTE						CL	WITH(NOLOCK)
ON		CA.ID_CLIENTE	=	CL.ID_CLIENTE
		INNER JOIN
		TB_CEDENTE						C	WITH(NOLOCK)
ON		CL.ID_CEDENTE	=	C.ID_CEDENTE
WHERE
		CA.ID_ACAO IN (SELECT ID_ACAO FROM TB_ACAO WITH(NOLOCK) WHERE NM_ACAO LIKE '%PREVENTIVO POSITIVO%')
	AND CAST(CA.DT_ACAO AS DATE) BETWEEN DATEADD(DD, -5, @DT_INICIAL) AND @DT_FINAL
	AND U.ID_EQUIPE	=	178
	AND CASE
		WHEN DATEDIFF(DD, PA.DT_PAGAMENTO, CAST(CA.DT_ACAO AS DATE)) BETWEEN -5 AND 0 THEN 1
		END = 1

DELETE	#TB_TEMP_PAGAMENTOS_ANALITICO_PREVENTIVO
WHERE
		NU_ORDEM_PREVENTIVO > 1


---PAGTOS TOTAL
IF OBJECT_ID('TEMPDB.DBO.#TB_TEMP_PAGAMENTOS', 'U') IS NOT NULL
DROP TABLE #TB_TEMP_PAGAMENTOS
SELECT
		  NU_CPF_CNPJ		
		, NM_USUARIO
		, QTD_PAGAMENTOS	=	COUNT(1)
		, VL_PAGAMENTO		=	SUM(VL_PAGO)
		, DT_ULT_PAGAMENTO	=	CAST(MAX(DT_PAGAMENTO) AS DATE)
INTO	#TB_TEMP_PAGAMENTOS
FROM	#TB_TEMP_PAGAMENTOS_ANALITICO	F WITH(NOLOCK)
GROUP	BY
		  NU_CPF_CNPJ
		, NM_USUARIO

---PAGTOS PREVENTIVO
IF OBJECT_ID('TEMPDB.DBO.#TB_TEMP_PAGAMENTOS_PREVENTIVO', 'U') IS NOT NULL
DROP TABLE #TB_TEMP_PAGAMENTOS_PREVENTIVO
SELECT
		  NU_CPF_CNPJ		
		, NM_USUARIO
		, QTD_PAGAMENTOS	=	COUNT(1)
		, VL_PAGAMENTO		=	CAST(SUM(VL_PAGO) * 0.33 AS DECIMAL(18,2))
		, DT_ULT_PAGAMENTO	=	CAST(MAX(DT_PAGAMENTO) AS DATE)
INTO	#TB_TEMP_PAGAMENTOS_PREVENTIVO
FROM	#TB_TEMP_PAGAMENTOS_ANALITICO_PREVENTIVO
GROUP	BY
		  NU_CPF_CNPJ
		, NM_USUARIO	


DELETE #TB_TEMP_PAGAMENTOS
WHERE
		NU_CPF_CNPJ IN (SELECT NU_CPF_CNPJ FROM #TB_TEMP_PAGAMENTOS_PREVENTIVO)

INSERT INTO #TB_TEMP_PAGAMENTOS
SELECT
		*
FROM	#TB_TEMP_PAGAMENTOS_PREVENTIVO

---ATUALIZA CARTEIRA DO CAPACITY
UPDATE	#TB_TEMP_CAPACITY
SET		CARTEIRA = 'PREVENTIVO'
WHERE
		NU_CPF_CNPJ IN (SELECT NU_CPF_CNPJ FROM #TB_TEMP_PAGAMENTOS_PREVENTIVO)

---PAGTOS CREDZ
IF OBJECT_ID('TEMPDB.DBO.#TB_TEMP_PAGAMENTOS_CREDZ', 'U') IS NOT NULL
DROP TABLE #TB_TEMP_PAGAMENTOS_CREDZ
SELECT
		  NU_CPF_CNPJ		=	NU_CPF_CNPJ_OPERADOR
		, NM_USUARIO		=	OPERADOR
		, QTD_PAGAMENTOS	=	COUNT(1)
		, VL_PAGAMENTO		=	SUM(VL_PAGTO)
		, DT_ULT_PAGAMENTO	=	CAST(MAX(DT_PAGAMENTO) AS DATE)
INTO	#TB_TEMP_PAGAMENTOS_CREDZ
FROM	[192.168.1.71].[DB_PLANEJAMENTO].[DBO].[TB_CARGA_PAGAMENTO_CREDZ]	WITH(NOLOCK)
WHERE
		DT_PAGAMENTO BETWEEN @DT_INICIAL AND @DT_FINAL
	AND NU_PARCELA = 1
	AND NU_CPF_CNPJ_OPERADOR IN (SELECT NU_CPF_CNPJ	FROM #TB_TEMP_CAPACITY WHERE CARTEIRA =	'CREDZ')
GROUP	BY
		  NU_CPF_CNPJ_OPERADOR
		, OPERADOR

DELETE	#TB_TEMP_PAGAMENTOS
WHERE
		NU_CPF_CNPJ IN (SELECT NU_CPF_CNPJ FROM #TB_TEMP_PAGAMENTOS_CREDZ WHERE NU_CPF_CNPJ IN (SELECT NU_CPF_CNPJ	FROM #TB_TEMP_CAPACITY WHERE CARTEIRA =	'CREDZ'))

INSERT INTO #TB_TEMP_PAGAMENTOS
SELECT
		*
FROM	#TB_TEMP_PAGAMENTOS_CREDZ
WHERE
		NU_CPF_CNPJ IN (SELECT NU_CPF_CNPJ	FROM #TB_TEMP_CAPACITY WHERE CARTEIRA =	'CREDZ')

---ATUALIZA AS METAS DE PONTUACAO VERRESCASH
UPDATE	#TB_TEMP_CAPACITY
SET		META_PONTO	=	CASE
						WHEN CARTEIRA = 'BAUDUCCO' THEN 5710
						WHEN CARTEIRA = 'C&A' THEN 160
						WHEN CARTEIRA = 'CEMIG' THEN 1943.63
						WHEN CARTEIRA = 'CREDZ' THEN 160
						WHEN CARTEIRA = 'DIGITAL' THEN 900
						WHEN CARTEIRA = 'DM' THEN 160
						WHEN CARTEIRA = 'MOVIDA PJ' THEN 3200
						WHEN CARTEIRA = 'MOVIDA RAC' THEN 550
						WHEN CARTEIRA = 'MOVIDA ZEROKM' THEN 2600
						WHEN CARTEIRA = 'PORTO CDC' THEN 2500
						WHEN CARTEIRA = 'PORTO SEM GARANTIA' THEN 250
						WHEN CARTEIRA = 'PORTO JURIDICO' THEN 820
						WHEN CARTEIRA = 'SERASA' THEN 750
						WHEN CARTEIRA = 'SERASA FEE' THEN 80
						WHEN CARTEIRA = 'SERASA FIXA' THEN 730
						WHEN CARTEIRA = 'SERASA REG' THEN 3500
						WHEN CARTEIRA = 'TORRA TORRA' THEN 120
						WHEN CARTEIRA = 'VILA VITORIA' THEN 2500
						WHEN CARTEIRA = 'SICREDI' THEN 535.77
						WHEN CARTEIRA = 'SUCUMBENCIA JURIDICO' THEN 255.03
						WHEN CARTEIRA = 'PORTO JURIDICO' THEN 820
						WHEN CARTEIRA = 'SICREDI JURIDICO' THEN 535.77
						WHEN CARTEIRA = 'PREVENTIVO' THEN 147.67	
						ELSE
						0
						END


---RELATORIO FINAL
SELECT		
		  C.CARTEIRA
		, P.NU_CPF_CNPJ
		, P.NM_USUARIO
		, P.VL_PAGAMENTO
		, VERRESCHI_CASH	=	CAST(P.VL_PAGAMENTO / C.META_PONTO AS INT)
		, C.META_PONTO
FROM	#TB_TEMP_PAGAMENTOS P
		INNER JOIN
		#TB_TEMP_CAPACITY	C
ON		P.NU_CPF_CNPJ	=	C.NU_CPF_CNPJ
WHERE
		C.META_PONTO  NOT IN (0)
ORDER	BY
	  	  CARTEIRA ASC
		, CAST(P.VL_PAGAMENTO / C.META_PONTO AS INT) DESC


        ";

        return DB::connection('easycollector')->select($sql, [
            'dtInicial' => $dtInicial,
            'dtFinal'   => $dtFinal
        ]);
    }
}
